### ISSUE TITLE
The training process

### ISSUE THREAD

**Issue by boileddd** [zju-vipa/ProtoPFormer#1]
hello, It's a nice work! But I don't understand the training process. Does it have the same training algorithm as ProtoPNet? or others? I don't really understand. I would appreciate it if you could answer this question.

**Comment by xmq1221** [comment]
Hi @boileddd, thanks for your interest! Our work is implemented based on the widely-used official codes of DeiT cause we aim to propose a method for part-prototype-based method for ViTs.  ViTs have quite different training processes and data augmentation strategies from CNNs. So in this repository, our training process is different from the process in the official codes of ProtoPNet.

For the whole training process, this repository has contained all the stages used in our experiment, please follow the readme document to train the ProtoPFormer model. And we have described more training details in the supplementary material which will be made publicly available soon.

**Comment by boileddd** [comment]
Thanks a lot for the reply! Your answer has solved my problem and I 'm looking forward to the supplementary material! This is a very good work, it may bother you again in the future, thank you again.

**Comment by xmq1221** [comment]
The supplementary material containing more training details and experiments will be uploaded soon. Please feel free to email me or raise an issue if you need any further information. Thanks for your interest in ProtoPFormer!
