### ISSUE TITLE
How to visualize global prototypes?

### ISSUE THREAD

**Issue by boileddd** [zju-vipa/ProtoPFormer#2]
hello, sorry to bother you. It seems that main_visualize.py only can visualize local prototypes. So how to visualize global prototypes？

**Comment by hqhQAQ** [comment]
Different from visualizing a local prototype, we select the attention rollout results of the most highly activated images to visualize a global prototype (i.e., the selected images have the highest activation on this global prototype). The detailed process of visualizing a global prototype will be updated in our code.
